### ISSUE TITLE
should not call return new Promise((resolve, reject) => {

### ISSUE THREAD

**Issue by capaj** [btomashvili/react-redux-firebase-boilerplate#1]
In the https://github.com/btomashvili/react-redux-firebase-boilerplate/blob/master/src/app/utils/firebase.js each method is constructing a new promise to return. This is a bad practice when you're internally calling functions which return a promise already. You should just chain your promises.

**Comment by bekatom** [comment]
@capaj  Thanks for your feedback. Will be fixed ;)

**Comment by capaj** [comment]
@btomashvili thanks, much nicer now.
