### ISSUE TITLE
Fix coding style?

### ISSUE THREAD

**Issue by EcutDavid** [btomashvili/react-redux-firebase-boilerplate#12]
Just cloned the repo and found that many errors prompted after `npm run test`.
![image](https://cloud.githubusercontent.com/assets/10692276/19711420/3511b0b8-9b68-11e6-8a36-987b1ef89168.png)

It should be fixed, otherwise, eslint will be kind of useless for people trying to build projects based on this repo.

**Comment by mortezaalizadeh** [comment]
Having the same problem here, any chance it can be fixed soon? Cheers

**Comment by mortezaalizadeh** [comment]
Fixed the issue in this pull request: https://github.com/btomashvili/react-redux-firebase-boilerplate/pull/20

**Comment by bekatom** [comment]
@mortezaalizadeh  thanks for contribution
