### ISSUE TITLE
Deploy to Firebase

### ISSUE THREAD

**Issue by devgripes** [btomashvili/react-redux-firebase-boilerplate#16]
Thanks for this boilerplate. Really happy using it.

I'm having troubles deploying to Firebase.
I did:
`firebase init`
`firebase deploy`

How did you deploy your app to Firebase?
Are you using `public` folder or `dist` for deploying the app to Firebase or what?

Thanks

**Comment by devgripes** [comment]
closing this issue, i figured it out :)

**Comment by danieljvdm** [comment]
@kuronaru could you tell me what you did?
