### ISSUE TITLE
Twitter authentication not working

### ISSUE THREAD

**Issue by TheoMer** [btomashvili/react-redux-firebase-boilerplate#2]
OS: Windows Pro 10
Browser: Chrome Version 52.0.2743.60 beta-m (64-bit)
NPM: version 3.9.5
Node: 6.2.2

So, I un-comment:

`<a href="#" className="btn btn-info bt-social" onClick={()=>{this.loginWithProvider("twitter")}} data-provider="twitter">Twitter</a>`

but when clicked, nothing happens, no pop-up windows is presented.

I'm expecting the same functionality,as when the facebook icon is clicked, that being the pop-up window is presented.

What's the issue here?

**Comment by TheoMer** [comment]
As a follow up, the specific error generated is:

`Uncaught Error: signInWithPopup failed: First argument "authProvider" must be a valid Auth provider.  - firebase.js:172`

**Comment by bekatom** [comment]
Yeah, Will be in near future!!!

**Comment by TheoMer** [comment]
@btomashvili Cool!! Do you have a eta in mind for this enhancement?

**Comment by bekatom** [comment]
sorry for later response.  I think I will have time for it  In early of September.

**Comment by bekatom** [comment]
@TheoMer  it's done now. you can look.

p.s : You need to turn  additional permissions to request email address in twitter app
