### ISSUE TITLE
npm build not working on Windows 'rm' not a windows command

### ISSUE THREAD

**Issue by westerhofffl** [btomashvili/react-redux-firebase-boilerplate#25]
Can someone help with the correct build script for window? Can change rm to rmdir, but not sure what the && equivalent is in windows>

Thanks!

**Comment by Sh1n1x** [comment]
For me just remove  `rm -rf dist && ` into package.json work :)

**Comment by dragos199993** [comment]
you can use the git terminal and just use the rm command like you are using a linux distribution :smiley:
