### ISSUE TITLE
How to serve static files?

### ISSUE THREAD

**Issue by missioeric** [btomashvili/react-redux-firebase-boilerplate#7]
Hi,

Thank you for the boilerplate. One question: how would I serve some static files?

I have a theme I'm trying to add that has a few .js and .css file that need to be served. I can't figure out how to do it.

i.e. in my index.html file

```
 <script src="./js/bootstrap-datetimepicker.js"></script>
  <script src="./js/bootstrap-selectpicker.js"></script>
```

**Comment by bekatom** [comment]
@missioeric  You can import  in  /app/index.js, or wherever you need it.

```
import './js/bootstrap-datetimepicker.js';
```

p.s You need to create you js folder inside app folder.

**Comment by missioeric** [comment]
Thanks.
