### ISSUE TITLE
How can implement Modular CSS on this project

### ISSUE THREAD

**Issue by daiky00** [btomashvili/react-redux-firebase-boilerplate#8]
How can implement Modular CSS on this project. this is what i have done so far in my webpack config.

```
  webpackConfig.module.loaders.push({
      test: /\.scss$/,
      loader: ExtractSASS.extract(['style', 'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]', 'sass']),
    });
  } else {
    webpackConfig.plugins.push(
      new Webpack.HotModuleReplacementPlugin()
    );

    webpackConfig.module.loaders.push({
      test: /\.scss$/,
      loaders: ['style','css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]', 'sass'],
    });

```

Is there something wrong with this.

also here is picture of my file structure

![image](https://cloud.githubusercontent.com/assets/15005162/18913447/cbb5d4aa-8555-11e6-9ac4-b2a63c8d8c86.png)

Please let me know what the best way to do this?

**Comment by bekatom** [comment]
There is already webpack scss loader in project.
You can import  your components .scss files in bundle.scss file.

In bundle.scss  file

```
@import './components/app';
```

app.scss file is under component folder which contains styles

```
body {
  font-size: 16px;
}

```

You can see my last commit now  607ee0feede407f82e3f4a0c72d331c8aeced5fe
